version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.11"
  jobs:
    pre_build:
     - sphinx-apidoc -F -H "App Store Server Library" -A "Apple Inc." -V "0.2.0" -e -a -o _staging . tests setup.py

sphinx:
  configuration: _staging/conf.py

python:
  install:
    - requirements: docs/requirements.txt
    - requirements: requirements.txt
    - method: pip
      path: .